// <auto-generated />
using System;
using BannerlordUnits.WebAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BannerlordUnits.WebAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class UnitsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BannerlordUnits.WebAPI.Models.CustomTroop", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Athletics")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Bow")
                        .HasColumnType("integer");

                    b.Property<int>("Crafting")
                        .HasColumnType("integer");

                    b.Property<int>("Crossbow")
                        .HasColumnType("integer");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("OneHanded")
                        .HasColumnType("integer");

                    b.Property<int>("Polearm")
                        .HasColumnType("integer");

                    b.Property<int>("Riding")
                        .HasColumnType("integer");

                    b.Property<int>("Throwing")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("TwoHanded")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("Wage")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("CustomTroops", (string)null);
                });

            modelBuilder.Entity("BannerlordUnits.WebAPI.Models.Troop", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Athletics")
                        .HasColumnType("integer");

                    b.Property<int>("Bow")
                        .HasColumnType("integer");

                    b.Property<int>("Crossbow")
                        .HasColumnType("integer");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("OneHanded")
                        .HasColumnType("integer");

                    b.Property<int>("Polearm")
                        .HasColumnType("integer");

                    b.Property<int>("Riding")
                        .HasColumnType("integer");

                    b.Property<int>("Throwing")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("TwoHanded")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("Wage")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("Troops", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
