global using BannerlordUnits.WebAPI.DataAccess;
global using BannerlordUnits.WebAPI.Apis;
global using Microsoft.EntityFrameworkCore;
global using System.Reflection;
global using System.Text;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.AspNetCore.Authorization;
global using BannerlordUnits.Models;
global using Microsoft.AspNetCore.Authentication.JwtBearer;